### ISSUE TITLE
undefined reference to `UK_ASSERT` in function `ukplat_lcpu_halt_irq`

### ISSUE THREAD

**Issue by nderjung** [unikraft/unikraft#1016]
### Describe the bug

When compiling against x86_64 and a kvm (qemu or fc) target, the following error occurs during link-time:

```
 E  /usr/bin/ld: /github/workspace/_helloworld/.unikraft/build/libkvmplat.o: in function `ukplat_lcpu_halt_irq':
 E  /github/workspace/plat/kvm/x86/lcpu.c:50: undefined reference to `UK_ASSERT'
 E  collect2: error: ld returned 1 exit status
 ```

This was introduced in #980.

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

https://github.com/unikraft/unikraft/actions/runs/5742321655
