### PR TITLE
plat/kvm/x86: Fix build error due to missing `assert.h` header

### LINKED ISSUE #1016: undefined reference to `UK_ASSERT` in function `ukplat_lcpu_halt_irq`
### Describe the bug

When compiling against x86_64 and a kvm (qemu or fc) target, the following error occurs during link-time:

```
 E  /usr/bin/ld: /github/workspace/_helloworld/.unikraft/build/libkvmplat.o: in function `ukplat_lcpu_halt_irq':
 E  /github/workspace/plat/kvm/x86/lcpu.c:50: undefined reference to `UK_ASSERT'
 E  collect2: error: ld returned 1 exit status
 ```

This was introduced in #980.

### Steps to reproduce

_No response_

### Expected behavior

_No response_

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

kvm

### Relevant log output

https://github.com/unikraft/unikraft/actions/runs/5742321655

### PR DESCRIPTION
**Pull request by mogasergiu**
Once the commit
dbfb886b5312 ("plat: Ensure IRQ's disabled in `ukplat_lcpu_halt_irq`") got merged, a new build error appeared:
```
 E  /usr/bin/ld: /github/workspace/_helloworld/.unikraft/build/libkvmplat.o: in function `ukplat_lcpu_halt_irq':
 E  /github/workspace/plat/kvm/x86/lcpu.c:50: undefined reference to `UK_ASSERT'
 E  collect2: error: ld returned 1 exit status
```

This happened due to `uk/assert.h` not being included.

Github-Fixes: #980

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): `x86_64`
 - Platform(s): `kvm`,
 - Application(s):

### CODE REVIEW

**Review by nderjung — APPROVED** [review]
It builds again! 🎉 

Reviewed-by: Alexander Jung <alex@unikraft.io>

**Review by jschlumpp — APPROVED** [review]
:+1: 

Reviewed-by: Marco Schlumpp <marco@unikraft.io>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>
