### PR TITLE
plat/xen: Fix Arm setup to work with new Xen console

### LINKED ISSUE #1506: `plat/xen`: Build error on Xen ARM64: undefined reference to `prepare_console`
### Describe the bug

Building for Xen on ARM64 results in error. This bug was introduced by #1464.

### Steps to reproduce

Build C Hello in the [`catalog-core` repository[(https://github.com/unikraft/catalog-core). Follow the steps:

1. Clone the repository:

   ```console
   git clone https://github.com/unikraft/catalog-core
   ```

1. Enter the `c-hello/` directory:

   ```console
   cd catalog-core/c-hello/
   ```
   
1. Switch to the `scripts` branch:

   ```console
   git checkout scripts
   ```

1. Build C Hello for Xen/ARM64:

   ```console
   ./build.xen.arm64
   ```

   The build error occurs.

### Expected behavior

Build doesn't fail.

### Which architectures were you using or does this bug affect?

arm64

### Which platforms were you using or does this bug affect?

xen

### Relevant log output

```shell
/usr/lib/gcc-cross/aarch64-linux-gnu/13/../../../../aarch64-linux-gnu/bin/ld: /home/razvan/orgs/unikraft/tmp/test-nginx-core/catalog-core/c-hello/out/c-hello_xen-arm64.elf.o: in function `_libxenplat_armentry':
/home/razvan/orgs/unikraft/tmp/test-nginx-core/catalog-core/repos/unikraft/plat/xen/arm/setup64.c:361: undefined reference to `prepare_console'
/home/razvan/orgs/unikraft/tmp/test-nginx-core/catalog-core/repos/unikraft/plat/xen/arm/setup64.c:361:(.text+0x2210): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `prepare_console'
/usr/lib/gcc-cross/aarch64-linux-gnu/13/../../../../aarch64-linux-gnu/bin/ld: /home/razvan/orgs/unikraft/tmp/test-nginx-core/catalog-core/repos/unikraft/plat/xen/arm/setup64.c:363: undefined reference to `init_console'
/home/razvan/orgs/unikraft/tmp/test-nginx-core/catalog-core/repos/unikraft/plat/xen/arm/setup64.c:363:(.text+0x2214): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `init_console'
collect2: error: ld returned 1 exit status
```

### PR DESCRIPTION
**Pull request by thass0**
This fixes a regression introduced in the `ukconsole` changes. The recent updates to the Xen console drivers removed the `prepare_console()` and `init_console()` functions in favor of calling the same code through the early init tab.

Fixes: #1506 

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://unikraft.org/docs/contributing/) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms; (Only checked if it builds)
 - [x] Ran the [`checkpatch.uk`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.uk) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): `arm64`
 - Platform(s): `xen`
 - Application(s): N/A

### CODE REVIEW

File: plat/xen/arm/setup64.c [hunk 1]
```diff
@@ -358,9 +358,5 @@ void _libxenplat_armentry(void *dtb_pointer, paddr_t physical_offset)
 	get_console();
 	get_xenbus();
 
-	prepare_console();
```
Comment (michpappas) [inline plat/xen/arm/setup64.c:361]: In order for this to work, besides these changes you also need to move `uk_boot_early_init()` after `get_console()` and `get_xenbus()`, as these populate `HYPERVISOR_start_info`.

```diff
diff --git a/plat/xen/arm/setup64.c b/plat/xen/arm/setup64.c
index 3495c8bd4..77c93323b 100644
--- a/plat/xen/arm/setup64.c
+++ b/plat/xen/arm/setup64.c
@@ -339,9 +339,6 @@ void _libxenplat_armentry(void *dtb_pointer, paddr_t physical_offset)
        /* Set up events. */
        init_events();
 
-       /* Do early init */
-       uk_boot_early_init(bi);
-
        /* Initialize logical boot CPU */
        r = lcpu_init(lcpu_get_bsp());
        if (unlikely(r))
@@ -358,9 +355,8 @@ void _libxenplat_armentry(void *dtb_pointer, paddr_t physical_offset)
        get_console();
        get_xenbus();
 
-       prepare_console();
-       /* Init console */
-       init_console();
+       /* Do early init */
+       uk_boot_early_init(bi);
 
        uk_boot_entry();
 }
```

Comment (thass0) [reply plat/xen/arm/setup64.c:361]: Thank you for figuring this out Michalis! I updated the commit.

**Review by michpappas — APPROVED** [review]
@thass0 thanks for updating, looks good now.

Reviewed-by: Michalis Pappas <michalis@unikraft.io>

@razvand I previously tested these changes, let me know if you'd like to have someone do an additional test before we merge.

**Comment by razvand** [comment]
@michpappas , I'm doing another round of tests. And I'm asking @andreistan26 to do another round himself. We should be able to merge it today (Wednesda, October 2, 2024).

**Review by andreistan26 — APPROVED** [review]
Looks good and it works. Thanks!

Reviewed-by: Andrei Stan [andreistan2003@gmail.com](mailto:andreistan2003@gmail.com)

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>

**Comment by michpappas** [comment]
Approved-by: Michalis Pappas <michalis@unikraft.io>
