### PR TITLE
plat/linuxu: Fix build errors introduced by #251

### LINKED ISSUE #409: Invalid storage class for functions in `linuxu`
### Describe the bug

Invalid storage classes were introduced in #251 and are used for the following functions in `linuxu` on `x86_64`:

- `sys_*`
- `set_tls_pointer`
- `cpuid`
- `save_extregs`
- `restore_extregs`
- `arch_extregs_size`
- `arch_init_extregs`
- `_init_cpufeatures`
- `write_cr3`
- `invlpg`
- `rdmsr`
- `rdmsrl`
- `wrmsr`
- `wrmsrl`
- `rdtsc`
- `inb`
- `inw`
- `inl`
- `inq`
- `outb`
- `outw`
- `outl`
- `mul64_32`
- `sw_*`

### Steps to reproduce

Configure the `helloworld` application to use `x86_64` on `linuxu`:

```bash
kraft -v configure -F \
  --arch x86_64 \
  --plat linuxu \
  -u helloworld@staging \
  -u unikraft@staging \
  --yes LIBPOSIX_LIBDL \
  --yes LIBPOSIX_PROCESS \
  --yes LIBPOSIX_USER \
  --yes LIBPOSIX_SYSINFO \
  --yes LIBVFSCORE \
  --yes LIBUKSWRAND \
  --yes LIBUKSP \
  --yes LIBUKBLKDEV \
  --yes LIBSYSCALL_SHIM
```

### Expected behavior

Should be able to compile and run.

### Which architectures were you using or does this bug affect?

x86_64

### Which platforms were you using or does this bug affect?

linuxu

### Relevant log output

```shell
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h: In function 'sys_fstat':
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h:122:19: error: invalid storage class for function 'sys_open'
  122 | static inline int sys_open(const char *pathname, int flags, ...)
      |                   ^~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h:143:19: error: invalid storage class for function 'sys_close'
  143 | static inline int sys_close(int fd)
      |                   ^~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h:166:19: error: invalid storage class for function 'sys_socket'
  166 | static inline int sys_socket(int domain, int type, int protocol)
      |                   ^~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h:174:19: error: invalid storage class for function 'sys_exit'
  174 | static inline int sys_exit(int status)
      |                   ^~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h:180:19: error: invalid storage class for function 'sys_clock_gettime'
  180 | static inline int sys_clock_gettime(k_clockid_t clk_id, struct k_timespec *tp)
      |                   ^~~~~~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h:197:21: error: invalid storage class for function 'sys_mmap'
  197 | static inline void *sys_mmap(void *addr, size_t len, int prot, int flags,
      |                     ^~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h:214:19: error: invalid storage class for function 'sys_sigaction'
  214 | static inline int sys_sigaction(int signum, const struct uk_sigaction *action,
      |                   ^~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h:224:19: error: invalid storage class for function 'sys_sigprocmask'
  224 | static inline int sys_sigprocmask(int how,
      |                   ^~~~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h:235:19: error: invalid storage class for function 'sys_arch_prctl'
  235 | static inline int sys_arch_prctl(int code, unsigned long addr)
      |                   ^~~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h:242:19: error: invalid storage class for function 'sys_pselect6'
  242 | static inline int sys_pselect6(int nfds,
      |                   ^~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h:255:19: error: invalid storage class for function 'sys_timer_create'
  255 | static inline int sys_timer_create(k_clockid_t which_clock,
      |                   ^~~~~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h:266:19: error: invalid storage class for function 'sys_timer_settime'
  266 | static inline int sys_timer_settime(k_timer_t timerid, int flags,
      |                   ^~~~~~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/syscall.h:277:19: error: invalid storage class for function 'sys_timer_delete'
  277 | static inline int sys_timer_delete(k_timer_t timerid)
      |                   ^~~~~~~~~~~~~~~~
In file included from /tmp/build/80754af9/built/unikraft/plat/common/include/uk/plat/common/tls.h:34,
                 from /tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:38:
/tmp/build/80754af9/built/unikraft/plat/linuxu/include/linuxu/tls.h:35:20: error: invalid storage class for function 'set_tls_pointer'
   35 | static inline void set_tls_pointer(unsigned long arg)
      |                    ^~~~~~~~~~~~~~~
In file included from /tmp/build/80754af9/built/unikraft/plat/common/include/uk/plat/common/cpu.h:38,
                 from /tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:39:
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:62:20: error: invalid storage class for function 'cpuid'
   62 | static inline void cpuid(__u32 fn, __u32 subfn,
      |                    ^~~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:71:20: error: invalid storage class for function 'save_extregs'
   71 | static inline void save_extregs(struct sw_ctx *ctx)
      |                    ^~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:93:20: error: invalid storage class for function 'restore_extregs'
   93 | static inline void restore_extregs(struct sw_ctx *ctx)
      |                    ^~~~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:113:20: error: invalid storage class for function 'arch_extregs_size'
  113 | static inline __sz arch_extregs_size(void)
      |                    ^~~~~~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:121:20: error: invalid storage class for function 'arch_init_extregs'
  121 | static inline void arch_init_extregs(struct sw_ctx *ctx)
      |                    ^~~~~~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:129:20: error: invalid storage class for function '_init_cpufeatures'
  129 | static inline void _init_cpufeatures(void)
      |                    ^~~~~~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:162:20: error: invalid storage class for function 'write_cr3'
  162 | static inline void write_cr3(unsigned long cr3)
      |                    ^~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:167:20: error: invalid storage class for function 'invlpg'
  167 | static inline void invlpg(unsigned long va)
      |                    ^~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:173:20: error: invalid storage class for function 'rdmsr'
  173 | static inline void rdmsr(unsigned int msr, __u32 *lo, __u32 *hi)
      |                    ^~~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:179:21: error: invalid storage class for function 'rdmsrl'
  179 | static inline __u64 rdmsrl(unsigned int msr)
      |                     ^~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:187:20: error: invalid storage class for function 'wrmsr'
  187 | static inline void wrmsr(unsigned int msr, __u32 lo, __u32 hi)
      |                    ^~~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:194:20: error: invalid storage class for function 'wrmsrl'
  194 | static inline void wrmsrl(unsigned int msr, __u64 val)
      |                    ^~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:200:21: error: invalid storage class for function 'rdtsc'
  200 | static inline __u64 rdtsc(void)
      |                     ^~~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:210:20: error: invalid storage class for function 'inb'
  210 | static inline __u8 inb(__u16 port)
      |                    ^~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:218:21: error: invalid storage class for function 'inw'
  218 | static inline __u16 inw(__u16 port)
      |                     ^~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:226:21: error: invalid storage class for function 'inl'
  226 | static inline __u32 inl(__u16 port)
      |                     ^~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:234:21: error: invalid storage class for function 'inq'
  234 | static inline __u64 inq(__u16 port_lo)
      |                     ^~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:245:20: error: invalid storage class for function 'outb'
  245 | static inline void outb(__u16 port, __u8 v)
      |                    ^~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:250:20: error: invalid storage class for function 'outw'
  250 | static inline void outw(__u16 port, __u16 v)
      |                    ^~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:255:20: error: invalid storage class for function 'outl'
  255 | static inline void outl(__u16 port, __u32 v)
      |                    ^~~~
/tmp/build/80754af9/built/unikraft/plat/common/include/x86/cpu.h:260:21: error: invalid storage class for function 'mul64_32'
  260 | static inline __u64 mul64_32(__u64 a, __u32 b)
      |                     ^~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:41:15: error: invalid storage class for function 'sw_ctx_size'
   41 | static size_t sw_ctx_size(void);
      |               ^~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:42:14: error: invalid storage class for function 'sw_ctx_init'
   42 | static void  sw_ctx_init(void *ctx, unsigned long sp, unsigned long tlsp);
      |              ^~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:43:14: error: invalid storage class for function 'sw_ctx_start'
   43 | static void  sw_ctx_start(void *ctx) __noreturn;
      |              ^~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:44:14: error: invalid storage class for function 'sw_ctx_switch'
   44 | static void  sw_ctx_switch(void *prevctx, void *nextctx);
      |              ^~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:52:15: error: invalid storage class for function 'sw_ctx_size'
   52 | static size_t sw_ctx_size(void)
      |               ^~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:57:13: error: invalid storage class for function 'sw_ctx_init'
   57 | static void sw_ctx_init(void *ctx,
      |             ^~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:74:13: error: invalid storage class for function 'sw_ctx_start'
   74 | static void sw_ctx_start(void *ctx)
      |             ^~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:89:13: error: invalid storage class for function 'sw_ctx_switch'
   89 | static void sw_ctx_switch(void *prevctx, void *nextctx)
      |             ^~~~~~~~~~~~~
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c: In function 'sw_ctx_callbacks_init':
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:105:20: warning: assignment makes '__attribute__((noreturn))' qualified function pointer from unqualified [-Wdiscarded-qualifiers]
  105 |  ctx_cbs->start_cb = sw_ctx_start;
      |                    ^
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c: In function 'sys_fstat':
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:107:1: error: expected declaration or statement at end of input
  107 | }
      | ^
At top level:
/tmp/build/80754af9/built/unikraft/plat/common/sw_ctx.c:100:6: warning: 'sw_ctx_callbacks_init' defined but not used [-Wunused-function]
  100 | void sw_ctx_callbacks_init(struct ukplat_ctx_callbacks *ctx_cbs)
      |      ^~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by vladandrew**
Fix build errors introduced by https://github.com/unikraft/unikraft/pull/251. 
We add a missing bracket and remove duplicate definitions of sys_open and
sys_close.

Signed-off-by: Vlad-Andrei Badoiu <vlad_andrei.badoiu@upb.ro>

### Prerequisite checklist

 - [x] Read the [contribution guidelines](https://docs.unikraft.org/contribute.html) regarding submitting new changes to the project;
 - [x] Tested your changes against relevant architectures and platforms;
 - [x] Ran the [`checkpatch.pl`](https://github.com/unikraft/unikraft/blob/staging/support/scripts/checkpatch.pl) on your commit series before opening this PR;
 - [ ] Updated relevant documentation.

### Base target

 - Architecture(s): [e.g. `x86_64` or N/A]
 - Platform(s): [e.g. `kvm`, `xen` or N/A]
 - Application(s): [e.g. `app-python3` or N/A]

### CODE REVIEW

**Review by razvanvirtan — APPROVED** [review]
Looks good on my side!

Reviewed-by: Răzvan Vîrtan <virtanrazvan@gmail.com>

**Review by razvand — APPROVED** [review]
Nice catch. Thanks, @vladandrew 

Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>
